- name: Gather VPC facts
  ec2_vpc_net_facts:
    filters:
      'tag:Name': '{{aws_vpc_name}}'
  register: vpc_facts

- name: Set VPC fact
  set_fact:
    net: '{{vpc_facts.vpcs[0]}}'
  when: vpc_facts is defined and vpc_facts.vpcs[0] is defined

- name: Delete the key pair
  ec2_key:
    name: '{{aws_key_pair_name}}'
    state: absent

- name: Delete the management subnet
  ec2_vpc_subnet:
    state: absent
    vpc_id: '{{ net.vpc_id }}'
    cidr: '{{aws_management_subnet_cidr}}'
  when: net is defined

- name: Delete the tunnel 01 subnet
  ec2_vpc_subnet:
    state: absent
    vpc_id: '{{net.vpc.id}}'
    cidr: '{{aws_tunnel1_subnet_cidr}}'
  when: net is defined

- name: Delete the spoke 01 subnet
  ec2_vpc_subnet:
    state: absent
    vpc_id: '{{net.vpc.id}}'
    cidr: '{{aws_spoke1_subnet_cidr}}'
  when: net is defined

- name: Delete the IGW
  ec2_vpc_igw:
    vpc_id: '{{ net.vpc_id }}'
    state: absent
    region: '{{aws_region}}'
  register: igw
  when: net is defined

- name: Delete the VPC
  ec2_vpc_net:
    cidr_block: '{{aws_vpc_cidr}}'
    name: '{{ aws_vpc_name }}'
    region: '{{aws_region}}'
    state: absent

- name: Clean Pod data file
  shell: '/bin/rm -rf secret_vars/{{ secret_vars_file_name }}.yml'
  args:
    warn: False
    
- name: Clean Pod Key Pair
  shell: '/bin/rm -rf secret_vars/{{aws_key_pair_name}}'
  args:
    warn: False
