- name: Launch the HUB router
  ec2:
    group_id: '{{ SECURITY_GROUP }}'
    count: 1
    instance_type: 't2.medium'
    private_ip: '{{aws_management_subnet_class_default}}.254'
    image: 'ami-062f4179'
    wait: yes
    region: '{{ aws_region }}'
    keypair: '{{ KEY_PAIR }}'
    vpc_subnet_id: '{{ MANAGEMENT_SUBNET }}'
    assign_public_ip: yes
    source_dest_check: no
    instance_tags:
      Name: '{{ hub_server_name }}'
      Pod: '{{lab_pod | string}}'
  register: hub

- name: Set EC2 fact
  set_fact:
    hub: '{{hub.instances[0]}}'

- name: Set DNS records
  route53:
    state: present
    zone: '{{lab_domain}}'
    record: '{{ hub_dns_record }}'
    type: A
    value: '{{ hub.private_ip }}'
    wait: yes
    overwrite: true
  register: dns

- name: 'Create {{ secret_vars_file_name }}.yml file inside the secret_vars directory'
  lineinfile:
    dest: 'secret_vars/{{secret_vars_file_name}}.yml'
    line: '---'
    create: yes

- name: 'Write vpc info to {{secret_vars_file_name}}.yml file inside the secret_vars directory'
  lineinfile:
    dest: 'secret_vars/{{secret_vars_file_name}}.yml'
    regexp: '^{{ item.regexp | upper }}'
    line: "{{ item.regexp | upper }}: {{ '\"' + item.line + '\"' }}"
  with_items:
    - { regexp: 'hub_public_ip', line: '{{ hub.public_ip }}' }
    - { regexp: 'hub_public_dns', line: '{{ hub_dns_record }}' }

- name: add host to group networking
  add_host:
    name: hub
    groups: networking
    ansible_ssh_private_key_file: secret_vars/key_pair_{{ lab_pod | string }}
    ansible_user: '{{ networking_server_ansible_ssh_user }}'
    ansible_network_os: ios
    ansible_become: yes
    ansible_become_method: enable
    ansible_connection: network_cli

- name: Attach ENI to tunnel1 subnet
  ec2_eni:
    instance_id: '{{ hub.id }}'
    device_index: 1
    private_ip_address: '{{aws_tunnel1_subnet_class_default}}.254'
    subnet_id: '{{TUNNEL1_SUBNET}}'
    region: '{{aws_region}}'
    security_groups: 
      - '{{SECURITY_GROUP}}'
    state: present
    attached: yes
    description: 'Tunnel 01 interface'
  register: tunnel1

- name: Update the ENI to allow delete on termination
  ec2_eni:
    region: '{{aws_region}}'
    eni_id: '{{tunnel1.interface.id}}'
    delete_on_termination: true
    source_dest_check: no

- name: Attach ENI to tunnel2 subnet
  ec2_eni:
    instance_id: '{{ hub.id }}'
    device_index: 2
    private_ip_address: '{{aws_tunnel2_subnet_class_default}}.254'
    subnet_id: '{{TUNNEL2_SUBNET}}'
    region: '{{aws_region}}'
    security_groups: 
      - '{{SECURITY_GROUP}}'
    state: present
    attached: yes
    description: 'Tunnel 02 interface'
  register: tunnel2

- name: Update the ENI to allow delete on termination
  ec2_eni:
    region: '{{aws_region}}'
    eni_id: '{{tunnel2.interface.id}}'
    delete_on_termination: true
    source_dest_check: no

- include_vars: 'secret_vars/{{ secret_vars_file_name }}.yml'
