- include_vars: 'secret_vars/{{ secret_vars_file_name }}.yml'

- name: Ensures the key destination folder exists
  file: 
    path: '/home/ubuntu/.ssh'
    state: directory

- name: Copy the key
  copy:
    src: '{{ KEY_PAIR_PATH }}'
    dest: '/home/ubuntu/.ssh'
    mode: 0600
    owner: ubuntu
    group: ubuntu

- name: Change hostname
  hostname:
    name: '{{ ec2_server_name | to_snake_case | replace("#", "") }}'
- name: Change hosts file
  lineinfile:
    path: /etc/hosts
    regexp: '^127.0.0.1'
    line: '127.0.0.1  {{ ec2_server_name | to_snake_case | replace("#", "")}}'
- name: Fix locale issue
  blockinfile:
    path: /etc/environment
    insertafter: EOF
    content: |
      LC_ALL=en_US.UTF-8
      LANG=en_US.UTF-8
- name: Add custom .bashrc
  blockinfile:
    path: /home/ubuntu/.bashrc
    insertafter: EOF
    content: |
      # Custom alias
      alias cls="clear"

      # Custom Prompt
      function prompt {
        local BLACK="\[\033[0;30m\]"
        local BLACKBOLD="\[\033[1;30m\]"
        local RED="\[\033[0;31m\]"
        local REDBOLD="\[\033[1;31m\]"
        local GREEN="\[\033[0;32m\]"
        local GREENBOLD="\[\033[1;32m\]"
        local YELLOW="\[\033[0;33m\]"
        local YELLOWBOLD="\[\033[1;33m\]"
        local BLUE="\[\033[0;34m\]"
        local BLUEBOLD="\[\033[1;34m\]"
        local PURPLE="\[\033[0;35m\]"
        local PURPLEBOLD="\[\033[1;35m\]"
        local CYAN="\[\033[0;36m\]"
        local CYANBOLD="\[\033[1;36m\]"
        local WHITE="\[\033[0;37m\]"
        local WHITEBOLD="\[\033[1;37m\]"
        local RESETCOLOR="\[\e[00m\]"

        export PS1="\n$RED\u$PURPLE@$(hostname) $GREEN\w $RESETCOLOR$GREENBOLD\$(git branch 2> /dev/null)\n $BLUE[\#] → $RESETCOLOR"
        export PS2=" | → $RESETCOLOR"
      }

      prompt
- name: Install Python 2.7
  apt:
    update_cache: true
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python

- name: Sets the python version to 2.7
  set_fact:
    ansible_python_interpreter: /usr/bin/python

- name: Pip, and Git
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python
      - python-pip
      - git

- name: Install docker-compose
  pip:
    name: docker-compose
    executable: /usr/bin/pip

- name: Clone Devops 101 repo
  git:
    repo: 'https://github.com/conapps/Devops-101.git'
    dest: /home/ubuntu/devops_101

- name: Symlink the ansible_lab folder to the user home
  file:
    src: '/home/ubuntu/devops_101/Advanced Network Programmability/ansible_lab'
    dest: '/home/ubuntu/ansible_lab'
    state: link

- name: Run the lab
  docker_service:
    project_src: '/home/ubuntu/ansible_lab/docker'
    build: yes
    project_name: Ansible Lab
  register: lab
